// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYniKrHoPvIFZJagpOu5iDaXWNIpWjE-Y',
    appId: '1:732747160919:web:3534bf45bd4dfbc76af212',
    messagingSenderId: '732747160919',
    projectId: 'fir-flutter-73543',
    authDomain: 'fir-flutter-73543.firebaseapp.com',
    storageBucket: 'fir-flutter-73543.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtIw1VgtCrK6oBKBS4rG0RzluoiN5C364',
    appId: '1:732747160919:android:6f8f39cb49a7c8556af212',
    messagingSenderId: '732747160919',
    projectId: 'fir-flutter-73543',
    storageBucket: 'fir-flutter-73543.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf5DNa6n1l5QaQSfiLm6aSQ7XPWgKEh1E',
    appId: '1:732747160919:ios:8ef77d929bdeeede6af212',
    messagingSenderId: '732747160919',
    projectId: 'fir-flutter-73543',
    storageBucket: 'fir-flutter-73543.appspot.com',
    iosClientId: '732747160919-f07ne8vuhufbev6tujijjlafuij7e2q1.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf5DNa6n1l5QaQSfiLm6aSQ7XPWgKEh1E',
    appId: '1:732747160919:ios:8ef77d929bdeeede6af212',
    messagingSenderId: '732747160919',
    projectId: 'fir-flutter-73543',
    storageBucket: 'fir-flutter-73543.appspot.com',
    iosClientId: '732747160919-f07ne8vuhufbev6tujijjlafuij7e2q1.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseflutter',
  );
}
